### ISSUE TITLE
Missing a full example

### ISSUE THREAD

**Issue by raphaelauv** [provectus/kafka-connect-vault-config-provider#13]
Thanks for this opensource vault provider

I could not make it work fully , the kafka-connect worker start correctly but when I submit a connector it fail

kafka connect worker config :
```yaml
      CONNECT_CONFIG_PROVIDERS: 'file,vault'
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'
      CONNECT_CONFIG_PROVIDERS_VAULT_CLASS: 'com.provectus.kafka.connect.config.VaultConfigProvider'
      CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_VAULT_AUTH_METHOD: token
      CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_URI: http://vault:8200
      CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_TOKEN: s.kunJxvnkfyXXXXXXXXXXX
```

Connector config : 

```json
"database.password": "${vault:cubbyhole/INVENTORY_CONNECTOR_POSTGRES:PASSWORD}",
```

The secret in vault : 
![Screenshot from 2021-08-02 23-29-19](https://user-images.githubusercontent.com/10202690/127926270-7b89544e-2f9a-46c9-8258-3737b06eac28.png)

If I curl the secret with the same token then the kafka-conect config

```shell
curl --header "X-Vault-Token: s.kunJxvnkfyXXXXXXXXXXX" localhost:8200/v1/cubbyhole/INVENTORY_CONNECTOR_POSTGRES
```

it answer 

```json
{"request_id":"d16b6c14-7a37-068d-346c-dad7a8bb107c","lease_id":"","renewable":false,"lease_duration":0,"data":{"PASSWORD":"postgres"},"wrap_info":null,"warnings":null,"auth":null}
```

but when I submit the connector I have this error : 

```json
{"error_code":500,"message":"com.bettercloud.vault.VaultException: Vault responded with HTTP status code: 404\nResponse body: {\"errors\":[]}\n"}(venv)
```

Thanks for your help.
